name: ESLint
on: push

jobs:
  # Label of the container job
  check-api-lint:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Define working directory into env.
    env:
      WORKING-DIR: ./API-v2
    # Docker Hub image that `container-job` executes in
    container: node:16

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: npm ci
        working-directory: ${{env.WORKING-DIR}}

      - name: Check linter
        # Run a linter check with eslint (with tslint plugin) to check
        # if the code is compliant 
        run: npm run lint
        working-directory: ${{env.WORKING-DIR}}
