name: Routes check
on: push

jobs:
  load-docker-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and load
        uses: docker/build-push-action@v2
        with:
          context: API-v2
          load: true
          tags: ardianethread/ardiane_api:test
      -
        name: Inspect
        run: |
          docker image inspect ardianethread/ardiane_api:test