---
name: Routes check
on: push

jobs:
  load-docker-image:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "ardiane"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and load
        uses: docker/build-push-action@v2
        with:
          context: API-v2
          load: true
          tags: ardianethread/ardiane_api:test
      -
        name: Inspect
        run: docker image inspect ardianethread/ardiane_api:test
      -
        name: Run the API
        run: docker run --name ardiane-api -p 9000:9000 -e DATABASE_DB=ardiane -e DATABASE_HOST=postgres --network postgres ardianethread/ardiane_api:test
      - 
        name: Pull newman image
        run: docker pull postman/newman
      - 
        name: Run postman collection
        run: docker run -t postman/newman run "https://www.getpostman.com/collections/e33ad8d28e164e80aed5"